name: Release to Github Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write # for committing to gh-pages branch
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Github-Pages-Release:
    timeout-minutes: 10
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # repo checkout

      # Install Rust Nightly Toolchain
      - name: Install nightly Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Lint
        run: cargo clippy && cargo fmt --check

      # Install Trunk
      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.20.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-

      # Build with Trunk
      - name: Build with Trunk
        run: ./trunk build --release --public-url "/${GITHUB_REPOSITORY#*/}"

      # GitHub Pages Setup and Deployment
      - name: Setup Pages
        uses: actions/configure-pages@v5 # latest as of now

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # v3 is latest for this action
        with:
          path: './dist'

      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4 # bumped to v4
